FROM openjdk:8-jdk

ARG KM_VERSION=1.3.3.17

WORKDIR /opt

RUN curl -fSL https://github.com/yahoo/kafka-manager/archive/${KM_VERSION}.tar.gz | \
    tar -zx --strip-components=1 && \
    ./sbt clean dist && \
    unzip -d /tmp ./target/universal/kafka-manager-${KM_VERSION}.zip && \
    mv /tmp/kafka-manager-${KM_VERSION} /tmp/kafka-manager

#FROM confluentinc/cp-base
